- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - "/var/lib/etcd"    # etcd 工作目录
  - "/etc/etcd/"

#
- name: 下载etcd二进制文件
  copy: src={{ local_bin_dir }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_etcd

- name: 分发证书相关
  copy: src={{ base_dir }}/ssl/{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - ca.pem
  - ca-key.pem
  - ca-config.json
  - etcd-key.pem
  - etcd.pem

- name: copy etcd.service
  template: src=etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service
  tags: upgrade_etcd

- name: 创建etcd配置文件
  template: src=etcd.conf.j2 dest={{ ETCD_CONFIG }}/etcd.conf
  tags: upgrade_etcd

#
- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true
#
- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd
#
- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd